# Generated by Django 4.2.2 on 2023-06-09 19:12

from django.db import migrations, models
import fluffyWeb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_bondName', models.CharField(default=None, max_length=210, unique=True)),
                ('user_displayName', models.CharField(max_length=200)),
                ('user_hashCode', models.IntegerField(default=0)),
                ('userId', models.CharField(default=None, max_length=50, unique=True)),
                ('pictureUrl', models.CharField(default=None, max_length=200, null=True)),
                ('pictureContent', models.ImageField(blank=True, null=True, upload_to=fluffyWeb.models.save_imagePath)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
