FROM python:3.11.0
ENV PYTHONUNBUFFERED 1 
RUN pip install --upgrade pip
RUN pip install django
RUN pip install mysqlclient
RUN pip install djangorestframework
RUN pip install django-filter
RUN pip install Pillow
RUN pip install requests
RUN pip install social-auth-app-django
RUN pip install django-quill-editor