version: '3'

services:
  web:
    build: .
    tty: true
    volumes:
      - ../:/workspace
    depends_on:
      - db

  # MySQL
  db:
    image: mysql:8.0.33
    container_name: aigent_mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: aigent_test_database
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: nz1colrow
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: aigent_test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_HOSTS=aigent_mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=p@ssw0rd
    ports:
    - 8080:80

volumes:
    mysql_data: